version: '3.9'

services:
  whishper:
    build:
      context: .
      dockerfile: Dockerfile
    # Override the image directive from the main compose file
    image: whishper-recording-whishper:dev
      
  translate:
    ports:
      - 5000:5000

  mongo:
    ports:
      - 27017:27017